# Generated by Django 5.1.6 on 2025-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_bank', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('account_balance', models.PositiveIntegerField()),
            ],
        ),
    ]
